// THIS FILE WAS AUTOMATICALLY GENERATED BY THE RUN TASK
// DO NOT EDIT THIS FILE, YOUR CHANGES WILL BE OVERWRITTEN ON NEXT RUN
#include<lib.h>
#include<iostream>
int main() {
  int a = 1, b =2;
    int c = sum(a, b);
    std::cout << c << std::endl;
}