// THIS FILE WAS AUTOMATICALLY GENERATED BY THE RUN TASK
// DO NOT EDIT THIS FILE, YOUR CHANGES WILL BE OVERWRITTEN ON NEXT RUN
#include <iostream>

using namespace std;

int main() {
  class student {
   private:
    /* data */
   public:
    void getData() { printf("Data"); }
  };
  student watashi;
  watashi.getData();

  return 0;
}