// THIS FILE WAS AUTOMATICALLY GENERATED BY THE RUN TASK
// DO NOT EDIT THIS FILE, YOUR CHANGES WILL BE OVERWRITTEN ON NEXT RUN
#include <iostream>
using namespace std;
int main() {
  int x = 0;
  do {
    x++;
    std::cout << x << std::endl;
    return 0;
  } while (x <= 10);
}
